version: "3"

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports: 
      - "443:443"

  vue:
    container_name: vue
    build: ./vue
    volumes:
      - ./vue/app:/app
    ports: 
      - "8080:8080"
    tty: true
    stdin_open: true